import { Product, Sale, StockMovement } from './types';

export const products: Product[] = [
  {
    id: '1',
    sku: 'HRD-001',
    name: 'Martillo de Acero 500g',
    category: 'Herramientas',
    brand: 'Stanley',
    price: 245.50,
    stock: 45,
    status: 'active',
  },
  {
    id: '2',
    sku: 'HRD-002',
    name: 'Destornillador Plano 6"',
    category: 'Herramientas',
    brand: 'Stanley',
    price: 89.90,
    stock: 120,
    status: 'active',
  },
  {
    id: '3',
    sku: 'PIN-001',
    name: 'Pintura Vinílica Blanca 4L',
    category: 'Pinturas',
    brand: 'Comex',
    price: 450.00,
    stock: 8,
    status: 'active',
  },
  {
    id: '4',
    sku: 'FER-001',
    name: 'Varilla Corrugada 3/8" 6m',
    category: 'Ferretería',
    brand: 'Deacero',
    price: 185.00,
    stock: 200,
    status: 'active',
  },
  {
    id: '5',
    sku: 'ELE-001',
    name: 'Cable Calibre 12 AWG',
    category: 'Eléctrico',
    brand: 'Condumex',
    price: 12.50,
    stock: 500,
    status: 'active',
  },
  {
    id: '6',
    sku: 'PLO-001',
    name: 'Tubo PVC 4" x 6m',
    category: 'Plomería',
    brand: 'Pavco',
    price: 320.00,
    stock: 25,
    status: 'active',
  },
  {
    id: '7',
    sku: 'HRD-003',
    name: 'Taladro Percutor 1/2"',
    category: 'Herramientas',
    brand: 'Black & Decker',
    price: 1250.00,
    stock: 12,
    status: 'active',
  },
  {
    id: '8',
    sku: 'FER-002',
    name: 'Cemento Gris 50kg',
    category: 'Ferretería',
    brand: 'Cemex',
    price: 285.00,
    stock: 3,
    status: 'active',
  },
  {
    id: '9',
    sku: 'PIN-002',
    name: 'Brocha 3" Profesional',
    category: 'Pinturas',
    brand: 'Truper',
    price: 95.00,
    stock: 65,
    status: 'active',
  },
  {
    id: '10',
    sku: 'ELE-002',
    name: 'Foco LED 15W',
    category: 'Eléctrico',
    brand: 'Philips',
    price: 125.00,
    stock: 150,
    status: 'active',
  },
  {
    id: '11',
    sku: 'HRD-004',
    name: 'Nivel de Aluminio 24"',
    category: 'Herramientas',
    brand: 'Truper',
    price: 320.00,
    stock: 28,
    status: 'active',
  },
  {
    id: '12',
    sku: 'PLO-002',
    name: 'Llave Ajustable 12"',
    category: 'Plomería',
    brand: 'Urrea',
    price: 275.00,
    stock: 40,
    status: 'active',
  },
];

export const stockMovements: StockMovement[] = [
  {
    id: '1',
    productId: '1',
    productName: 'Martillo de Acero 500g',
    type: 'in',
    quantity: 50,
    reason: 'Compra a proveedor',
    date: '2026-02-20T10:30:00',
  },
  {
    id: '2',
    productId: '3',
    productName: 'Pintura Vinílica Blanca 4L',
    type: 'out',
    quantity: 5,
    reason: 'Venta mayoreo',
    date: '2026-02-22T14:15:00',
  },
  {
    id: '3',
    productId: '8',
    productName: 'Cemento Gris 50kg',
    type: 'adjustment',
    quantity: -2,
    reason: 'Ajuste por inventario físico',
    date: '2026-02-25T09:00:00',
  },
];

export const salesHistory: Sale[] = [
  {
    id: 'SALE-001',
    date: '2026-02-27T09:30:00',
    total: 1045.40,
    paymentMethod: 'cash',
    seller: 'María González',
    discount: 0,
    tax: 95.40,
    subtotal: 950.00,
    items: [
      { product: products[0], quantity: 2 },
      { product: products[1], quantity: 5 },
    ],
  },
  {
    id: 'SALE-002',
    date: '2026-02-27T10:15:00',
    total: 1770.00,
    paymentMethod: 'card',
    seller: 'María González',
    discount: 30,
    tax: 160.00,
    subtotal: 1600.00,
    items: [
      { product: products[2], quantity: 3 },
      { product: products[5], quantity: 1 },
    ],
  },
  {
    id: 'SALE-003',
    date: '2026-02-27T11:45:00',
    total: 337.50,
    paymentMethod: 'transfer',
    seller: 'Carlos Ramírez',
    discount: 0,
    tax: 37.50,
    subtotal: 300.00,
    items: [
      { product: products[3], quantity: 1 },
      { product: products[8], quantity: 1 },
    ],
  },
  {
    id: 'SALE-004',
    date: '2026-02-26T15:20:00',
    total: 1462.50,
    paymentMethod: 'cash',
    seller: 'María González',
    discount: 50,
    tax: 162.50,
    subtotal: 1300.00,
    items: [
      { product: products[6], quantity: 1 },
      { product: products[9], quantity: 5 },
    ],
  },
  {
    id: 'SALE-005',
    date: '2026-02-26T12:00:00',
    total: 880.00,
    paymentMethod: 'card',
    seller: 'Carlos Ramírez',
    discount: 20,
    tax: 80.00,
    subtotal: 800.00,
    items: [
      { product: products[10], quantity: 2 },
      { product: products[11], quantity: 1 },
    ],
  },
];
